---
title: "Data exploration"
output: html_document
---

```{r setup, include=FALSE}
dir_data <- "D:/HOME/ekamir/scoring_medscope/data/emmah" 
dir_plot <- "D:/HOME/ekamir/scoring_medscope/figure" 

library(s2dverification)
library(stats)
library(s2dverification)
library(ggplot2)
library(CSTools)

```

## Retrieving original data set

we have to do a trick to find out the first bootstrapped iteration and the run index whithin this iteration matching the year we are interested in (the random sampling doesn't respect chronology)

```{r }
indicateur <- "DRAIN"
load(file = file.path(dir_data, "extract", "years.RData")) # list of years in each bootstrap iteration

nom_ref <- paste0(indicateur,1,"_ref.RData")
load(file = file.path(dir_data, "extract", nom_ref))
ngrids <- dim(array_obs)[1]

ps_original <- array(NA, dim=c(ngrids, nan, nrun, ndimT))
ref_original <- array(NA, dim=c(ngrids, nan, ndimT))

 for (year in an){
 y <- which(an==year)
       # bootstrap iteration index of the year selected
     
    list_match <- lapply(rand_year, function(x) which(year == x)) # list of matchs between list of years randomly generated for the bootstrap and the year we are interested in
     
     y_index <- list_match[[1]] # year index within the bootstrap iteration
     b_index <- 1 # bootstrap iteration index
     for (b in 1:(nboot-1)){ # pick the first iteration and first index matching the year we are looking for
       if (length(list_match[[b]])<1 & length(y_index)<1) {y_index <- list_match[[b+1]]; b_index <- b+1}
       else {y_index <- y_index; b_index <- b_index}
     }
     
  nom_prev <- paste0(indicateur,b_index,"_prev.RData")
  load(file = file.path(dir_data, "extract", nom_prev))
  ps_original[,y,,] <- array_prev[,y_index[1],,]
  
  nom_ref <- paste0(indicateur,b_index,"_ref.RData")
  load(file = file.path(dir_data, "extract", nom_ref))
  ref_original[,y,] <- array_obs[,y_index[1],]
}

```
## Plotting seasonal prevision and observation

Attention sum ou mean selon indicateur!

```{r }

ps_season_int <- apply(ps_original, c(1,2,3), sum)
ps_season <- apply(ps_season_int, 2, mean)
ref_season_int <- apply(ref_original, c(1,2), sum)
ref_season <- apply(ref_season_int, 2, mean)

df_raw <- data.frame()
for (y in 1:nan){

  df_raw <- rbind(df_raw, data.frame(type = "prevision", year=an[y], value = ps_season[y]))
  df_raw <- rbind(df_raw, data.frame(type = "ref", year=an[y], value = ref_season[y]))

}
#aes(fill=type, colour=type)
ggplot(df_raw, aes(x=year, y=value,  fill=type)) + geom_bar(stat = "identity", position = "dodge")+
  labs(title = paste0(indicateur, " seasonal aggregation"), x="Year", y= "Value")+
      theme_bw()+
       scale_x_continuous(breaks = scales::pretty_breaks(n = 12))

# calculating mean differences
df_raw %>% group_by(type) %>% summarise(mean_ps=mean(value))

```
