---
title: "Mapping deterministic scores"
output: html_document
---

```{r setup, include=FALSE}
dir_data <- "D:/HOME/ekamir/scoring_medscope/data/season_trial2" 
dir_plot <- "D:/HOME/ekamir/scoring_medscope/figure" 
library(maps)
library(maptools)
library(tmaptools)
library(rasterVis)
library(ggplot2)
library(latticeExtra)
library(sp)
library(raster)
library(rgdal)
library(tmap)
library(sf)
library(ggmap)
library(mapview)
library(grid)
library(ggpubr)
library(rgeos)
```

## Parameter specifications

Indicator to be displayed
Region of interest

```{r}

moi <- c("May","June","July","August","September","October","November")

ind_fr <- c("Pluie – evaporation", "Somme des pluies","Nombre de jours de pluie","Nombre de jours T max > 25°C", 
             "Nombre de jours T max > 35°C", "Moyenne T max","Moyenne T min","Moyenne T moy")
ind_eng <- c("Rain – evaporation", "Accumulated rainfall","Number of rainy days","Number of days T max > 25°C", 
             "Number of days T max > 35°C", "T max mean","T min mean","T mean mean")

```
### LOADING RASTER FILES ###


```{r}

indicateur <- "DRAIN"
title <- paste0(indicateur,"_detseas",".tif")
stacky_seas <- stack(file.path(dir_plot, "emmah_raster", title)) # loading stack file

load(file = file.path(dir_plot, "season_raster", "layname_detseas.RData")) # loading stack layer names before writeraster changed them
names(stacky_seas) <- c(layername)# re setting original layer names

score_palette <- c("#ca0020","#f4a582","#f7f7f7","#92c5de","#0571b0")
drain <- c(-0.0016, 0.0016)
etp <- c(-0.006, 0.006)
```

### SEASON MAPS ###


```{r}
### BACKGROUND LOADED FROM GOOGLE
# key = "AIzaSyCD2-pP0yfM8aC8sjCB4g--CaCcExP6NhU"; "AIzaSyB24WUzCzX1lErLgsVLtio1c7QxLfw1_SA"
# register_google(key = "AIzaSyB24WUzCzX1lErLgsVLtio1c7QxLfw1_SA")
# back_map <- get_map(location = c(4, 43.1, 5.7, 44), maptype = "satellite", source = "google")  

  sp_msess <- rasterToPolygons(stacky_seas[[2]]) 
  names(sp_msess) <- "msess"
  shp_msess <- st_as_sf(sp_msess)

  # shapefile of prevision confidence
  sp_sign <- rasterToPoints(stacky_seas[[3]], spatial = TRUE)
  names(sp_sign) <- "significance"
  sp_sign$significance[which(sp_sign$significance==0)] <- NA # to help plotting
  sf_test <- st_as_sf(sp_sign)
  sf_nrm <- remove_missing(sf_test)
  
  sp_si <- rasterToPolygons(stacky_seas[[3]])
  sp_pt2 <- st_as_sf(sp_si)
  sp_pt <- st_centroid(sp_pt2,byid=TRUE)
  
  #shp_tercile$tercile <- as.factor(shp_tercile$tercile)
### OVERLAYING SHAPEFILE ON GOOGLE BACKGROUND MAP
ggmap(back_map) +
  geom_sf(data = shp_msess, aes(fill = msess), inherit.aes = FALSE, alpha = 1)+
  continuous_scale(aesthetics = "msess", scale_name = "manual", palette = 0.1)+
  scale_fill_gradientn(colours=score_palette, limits = drain)+  #
  geom_sf(data = sf_nrm, aes(colour = significance), inherit.aes = FALSE, size = 0.02, show.legend = FALSE)+
  labs(title = paste0(indicateur," season MSESS "))+
  theme(plot.title = element_text(size = 12, hjust = 0, vjust = 1.5))

```
