---
title: "Mapping deterministic scores"
output: html_document
---

```{r setup, include=FALSE}
dir_data <- "D:/HOME/ekamir/scoring_medscope/data/stics" 
dir_plot <- "D:/HOME/ekamir/scoring_medscope/figure" 

library(plotrix)
library(maps)
library(maptools)
library(ggplot2)
library(latticeExtra)
library(sp)
library(raster)
library(rgdal)
library(tmap)
library(sf)
library(ggmap)
library(maps)
library(ggplot2)
library(latticeExtra)
library(sp)
library(raster)
library(rgdal)
library(tmap)
library(sf)
library(ggmap)
library(mapview)
library(grid)

limits <- c(-1,1)
```


## Plotting spatial points

No error

```{r }

indicateur <- "grassyieldC1C2_"

nom_ref <- paste0(indicateur,b,"_ref.RData")
load(file = file.path(dir_data, "extract", nom_ref))
ngrids <- dim(array_obs)[1]

score_ps <- array(NA, dim=c(ngrids, nscore, nboot)) 

  for (b in 1:nboot)  { 
  
    nom_prev <- paste0(indicateur, b,"scoredetseas_grid_prev.RData")
    load(file = file.path(dir_data, "score", nom_prev))

    score_ps[,,b] <- det_seas[,]

  }
   
load(file = file.path(dir_data, "extract", paste0("lat_",indicateur,".RData")))
load(file = file.path(dir_data, "extract", paste0("lon_",indicateur,".RData")))
  
matrix4shp <- matrix(0, nrow = ngrids, ncol = 4) # col: skill score, significant, lat, lon 
matrix4shp[,3] <- unlist(lat)
matrix4shp[,4] <- unlist(lon)
  
## creating a table containing mean skill and wilcoxon test outcome, with both coordinates (shape ready for shapefile conversion)

matrix4shp[,2] <- rep(0, ngrids)
matrix4shp[,1] <- apply(score_ps[,1,], 1, mean, na.rm = TRUE) # select MSESS and summarize over bootstrap

for (i in 1:ngrids)  { 
    
  wmsess <- wilcox.test(score_ps[i,1,], mu = 0, alternative = "greater", conf.level = 0.95)
  # wbia <- wilcox.test(x = abs(score_clim[i,t,2,]), y = score_ps[i,t,2,] ,alternative = "greater", paired = TRUE, conf.level = 0.95)
  # wrms <- wilcox.test(x = score_clim[i,t,3,], y = score_ps[i,t,3,] ,alternative = "greater", paired = TRUE, conf.level = 0.95)
 
  if (wmsess$p.value < 0.05) {
    matrix4shp[i,2] <- 1 
  }
}

# we load the dataframe previously built and transform it into a raster
df_shp <- data.frame(matrix4shp)
colnames(df_shp) <- c("msess", "significance","lat","lon")
coordinates(df_shp) <- ~lon+lat
proj4string(df_shp) <- CRS("+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0")
#names(sp_grid) <- "grid"
#sp_grid$grid[which(sp_grid$grid==0)] <- NA # to help plotting
shp_grid <- st_as_sf(df_shp)

ggmap(back_map) +
geom_sf(data = shp_grid, aes(color = msess), size=4)+
  scale_color_gradientn(colours=score_palette)+
theme(plot.title = element_text(size = 12, hjust = 0, vjust = 1.5))+
  labs(title = paste0(indicateur," season MSESS "))


```
### Plotting spatial polygon from raster

works fine but grids too small and misplaced


```{r }
ngrids <-23
score_ps <- array(NA, dim=c(ngrids, nscore, nboot)) 

  for (b in 1:nboot)  { 
  
    nom_prev <- paste0(indicateur, b,"scoredetseas_grid_prev.RData")
    load(file = file.path(dir_data, "score", nom_prev))

    score_ps[,,b] <- det_seas[,]

  }
   
load(file = file.path(dir_data, "extract", paste0("lat_",indicateur,".RData")))
load(file = file.path(dir_data, "extract", paste0("lon_",indicateur,".RData")))
  
matrix4shp <- matrix(0, nrow = ngrids, ncol = 4) # col: skill score, significant, lat, lon 
matrix4shp[,3] <- unlist(lat)
matrix4shp[,4] <- unlist(lon)

## creating a table containing mean skill and wilcoxon test outcome, with both coordinates (shape ready for shapefile conversion)

matrix4shp[,2] <- rep(0, ngrids)
matrix4shp[,1] <- apply(score_ps[,1,], 1, mean, na.rm = TRUE) # select MSESS and summarize over bootstrap

for (i in 1:ngrids)  { 
    
  wmsess <- wilcox.test(score_ps[i,1,], mu = 0, alternative = "greater", conf.level = 0.95)

    if (wmsess$p.value < 0.05) {
      matrix4shp[i,2] <- 1 
    }
  }
    
# We create a 3 layer-raster: 1st with grid ID (useless), 2nd with msess score; 3rd with wilcoxon test outcomes. 
    
  # we load the dataframe previously built and transform it into a raster
df_shp <- data.frame(matrix4shp)
colnames(df_shp) <- c("msess", "significance","lat","lon")
coordinates(df_shp) <- ~lon+lat
proj4string(df_shp) <- CRS("+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0")
ras_prev <- raster(shp_det)
ext_prev <- extent(ras_prev)
mask.raster <- raster(nrows=length(lat), ncols=length(lon),
                   xmn=min(lon),xmx=max(lon),ymn=min(lat), ymx=max(lat))
ras_seas <- rasterize(df_shp, mask.raster) 
sp_msess <- rasterToPolygons(ras_seas[["msess"]]) 
names(sp_msess) <- "msess"
shp_msess <- st_as_sf(sp_msess)

  # shapefile of significance
sp_sign <- rasterToPoints(ras_seas[["significance"]], spatial = TRUE)
names(sp_sign) <- "significance"
sp_sign$significance[which(sp_sign$significance==0)] <- NA # to help plotting
sf_test <- st_as_sf(sp_sign)
sf_nrm <- remove_missing(sf_test)
  
### OVERLAYING SHAPEFILE ON GOOGLE BACKGROUND MAP
ggmap(back_map) +
  geom_sf(data = shp_msess, aes(fill = msess), inherit.aes = FALSE, alpha = 1)+
  continuous_scale(aesthetics = "msess", scale_name = "manual", palette = 0.1)+
  scale_fill_gradientn(colours=score_palette)+ #, limits = drain , limits = day25
  geom_sf(data = sf_nrm, aes(colour = significance), inherit.aes = FALSE, size = 0.02, show.legend = FALSE)+
  labs(title = paste0(indicateur," season MSESS "))+
  theme(plot.title = element_text(size = 12, hjust = 0, vjust = 1.5))
```

### meteo france


```{r }
 score <- apply(score_ps[,1,], 1, mean, na.rm = TRUE)

          matscore=matrix(score,nrow=length(lat),ncol=length(lon))
          r=raster(resolution = c(0.07,0.07),
                   xmn=min(lon),xmx=max(lon),ymn=min(lat), ymx=max(lat)) #nrows=length(lat), ncols=length(lon)
          r[]=matscore  
          
# niveau=drain
# niveau=seq(0,1,0.1)
# coleti=rev(c("#610B0B","#8B0000","#FF0000","#FA5858","#F5A9A9",
#                        "#A9A9F5","#5858FA","#0000FF","#0404B4","#0B0B61"))
# 
# grille_x=10 # ecartement (en degres) du cadrillage lat/lon des graphiques
# grille_y=10
# 
#           p=levelplot(r,margin=F,at=niveau,colorkey=list(at=niveau,labels=list(at=niveau)),
#                       col.regions=coleti,
#                       main=list(label="titre",cex=1),
#                       xlab=list(label=""),ylab=list(label=""),
#                       scales=list(cex=.7,
#                                   x=list(at=seq(round(xmin(extent(r)),-1),round(xmax(extent(r)),-1),grille_x)),
#                                   y=list(at=seq(round(ymin(extent(r)),-1),round(ymax(extent(r)),-1),grille_y))))
#           

   sp_si <- rasterToPolygons(r)
   names(sp_si) <- "msess"
   shp_msess <- st_as_sf(sp_si)
   
ggmap(back_map) +
  geom_sf(data = shp_msess, aes(fill = msess), inherit.aes = FALSE, alpha = 1)+
  continuous_scale(aesthetics = "msess", scale_name = "manual", palette = 0.1)+
  scale_fill_gradientn(colours=score_palette)+ #, limits = drain , limits = day25
  geom_sf(data = sf_nrm, aes(colour = significance), inherit.aes = FALSE, size = 0.02, show.legend = FALSE)+
  labs(title = paste0(indicateur," season MSESS "))+
  theme(plot.title = element_text(size = 12, hjust = 0, vjust = 1.5))


```
