---
title: "Memory effect"
output:
  word_document: default
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE, echo=FALSE}

library(plyr)
library(dplyr)
library(tidyverse)
library(stats)

```

## Parameters 

```{r }

                                     ### SELECTED PARAMETERS (to be set by user) ###

# selecting project
selected_project <- "stics" # stics or season or tree
# directories and cores
setup(project = selected_project, no_cores = 6)
# variable
indicateur <- indicateurs[4]

                                      ### LOADED PARAMETERS (permanent) ###


# loading number of bootstrap interations
load(file = file.path(dir_data, "extract", "nboot.RData"))

# loading variables
load(file = file.path(dir_data, "extract", "indicateurs.RData"))
# loading time scales and agregation type
load(file = file.path(dir_data, "extract", "temporalite.RData")) # is there a time dimension
load(file = file.path(dir_data, "extract", "time_window.RData")) # if yes which window is selected
load(file = file.path(dir_data, "extract", "agregation.RData")) # if yes what type of aggregation should be applied

ntemp <- length(temp) # number of elements in time dimension

# loading ensemble members
load(file = file.path(dir_data, "extract", "runs.RData"))
nrun <- length(run) # number of members

# loading years
load(file = file.path(dir_data, "extract", "years.RData"))
nan <- length(an) # number of years

```

## Loading and shaping data

```{r }

d <- which(indicateurs==indicateur)
temporalite <- time_scale[d] # select corresponding time dimension: single or multi
agreg <- agreg_type[d] # select corresponding time aggregation type: sum or mean

nom_ref <- paste0(indicateur,1,"_ref_uerra5.RData")
load(file = file.path(dir_data, "extract", nom_ref))
ngrids <- dim(array_obs)[1] # trick to automatically get number of grids


                                            ### WITH TIME DIMENSION ###
if (temporalite=="multi"){

clim_original <- array(NA, dim=c(ngrids, nan, nrun, ntemp))
ref_original <- array(NA, dim=c(ngrids, nan, ntemp))

 for (year in an){
 y <- which(an==year)

       # bootstrap iteration index of the year selected
    load(file = file.path(dir_data, "extract", "rand_years.RData")) # list of years in each bootstrap iteration
     
    list_match <- lapply(rand_year, function(x) which(year == x)) # list of matchs between list of years randomly generated for the bootstrap and the year we are interested in
     
     y_index <- list_match[[1]] # year index within the bootstrap iteration
     b_index <- 1 # bootstrap iteration index
     for (b in 1:(nboot-1)){ # pick the first iteration and first index matching the year we are looking for
       if (length(list_match[[b]])<1 & length(y_index)<1) {y_index <- list_match[[b+1]]; b_index <- b+1}
       else {y_index <- y_index; b_index <- b_index}
     }
     
  nom_clim <- paste0(indicateur,b_index,"_clim_uerra5.RData")
  load(file = file.path(dir_data, "extract", nom_clim))
  clim_original[,y,,] <- array_clim[,y_index[1],,temp]
  
  nom_ref <- paste0(indicateur,b_index,"_ref_uerra5.RData")
  load(file = file.path(dir_data, "extract", nom_ref))
  ref_original[,y,] <- array_obs[,y_index[1],temp]
}


                                            ### WITHOUT TIME DIMENSION ###
} else if (temporalite=="single"){


clim_original <- array(NA, dim=c(ngrids, nan, nrun))
ref_original <- array(NA, dim=c(ngrids, nan))

 for (year in an){
 y <- which(an==year)

       # bootstrap iteration index of the year selected
    load(file = file.path(dir_data, "extract", "years.RData")) # list of years in each bootstrap iteration
     
    list_match <- lapply(rand_year, function(x) which(year == x)) # list of matchs between list of years randomly generated for the bootstrap and the year we are interested in
     
     y_index <- list_match[[1]] # year index within the bootstrap iteration
     b_index <- 1 # bootstrap iteration index
     for (b in 1:(nboot-1)){ # pick the first iteration and first index matching the year we are looking for
       if (length(list_match[[b]])<1 & length(y_index)<1) {y_index <- list_match[[b+1]]; b_index <- b+1}
       else {y_index <- y_index; b_index <- b_index}
     }
     
  nom_clim <- paste0(indicateur,b_index,"_clim_uerra5.RData")
  load(file = file.path(dir_data, "extract", nom_clim))
  clim_original[,y,] <- array_clim[,y_index[1],]
  
  nom_ref <- paste0(indicateur,b_index,"_ref_uerra5.RData")
  load(file = file.path(dir_data, "extract", nom_ref))
  ref_original[,y] <- array_obs[,y_index[1]]
}

}

ngrids <- dim(ref_original)[1]


### RESHAPING ###

# FOR ANOVA: we build a 3 columns data frame: grid, year, value

df_out <- data.frame()

for (r in 1:nrun){
  if (temporalite=="single"){
    int <- as.data.frame(clim_original[,,r])
  }else if (temporalite=="multi"){ 
          if (agreg=="sum"){
    int <- as.data.frame(apply(clim_original[,,r,], c(1,2), sum))
    }else if (agreg=="mean"){
    int <- as.data.frame(apply(clim_original[,,r,], c(1,2), sum)) }
  }
    colnames(int) <- an
    int <- int %>% gather(an) %>% mutate(maille=rep(seq(1,ngrids,1), times=nan))
    df_out <- rbind(df_out, int)
}

# FOR SPECIFIC GRAPHS: time aggregation & ensemble mean
#grid means are needed for boxplot; ensemble means are needed for the prob time series

                                            ### WITH TIME DIMENSION ###
if (temporalite=="multi"){
      if (agreg=="sum"){
      clim_agreg <- apply(clim_original[,,,], c(1,2,3), sum)
      ref_agreg <- apply(ref_original[,,], c(1,2), sum)
      } else if (agreg=="mean"){
      clim_agreg <- apply(clim_original[,,,], c(1,2,3), mean)
      ref_agreg <- apply(ref_original[,,], c(1,2), mean)
      }
      
clim_gridmean <- apply(clim_agreg, c(2,3), mean)
clim_ensmean <- apply(clim_agreg, c(1,2), mean)
clim_original <- clim_agreg
ref_gridmean <- apply(ref_agreg, 2, mean)
ref_original <- ref_agreg



                                            ### WITHOUT TIME DIMENSION ###
} else if (temporalite=="single"){

clim_gridmean <- apply(clim_original, c(2,3), mean)
clim_ensmean <- apply(clim_original, c(1,2), mean)
ref_gridmean <- apply(ref_original, 2, mean)

}

```

## Implementing ANOVA

```{r }

fit1 <- aov(data = df_out, formula = value ~ an + maille + an:maille)
fit2 <- aov(data = df_out, formula = value ~ an )
summary(fit1)
summary(fit2)

newfit <- lm(data = df_out, formula = value ~ factor(an))
analyse <- anova(newfit)
analyse

```
## Verification plots

```{r }

fit <- aov(data = df_out, formula= value ~ an+maille)
plot(fit)

```

## Exploration plots: first overview

```{r }

                                 ### log VALUE VS GRID BOXPLOT ###
                                   

par(mfrow=c(1,2))
boxplot(log(value) ~ an, data=df_out, cex.lab=1.5, xlab="year",ylab="log(value)")
boxplot(log(value) ~ maille, data=df_out, cex.lab=1.5, xlab="maille",ylab="log(value)")
# interactions: boxplot(log(value) ~ an*maille, data=df_out, cex.lab=1.5, xlab="combinaison annee et maille ",ylab="log(value)")



```

## Exploration plots: zooming on year factor

```{r }
                                        ### VALUE MEAN VS GRID, YEAR EFFECT ###

with(df_out, {interaction.plot(x.factor = maille, trace.factor=an, response = value, type="l", fun=mean)},
abline(h=mean(value[an==2002]),col="red"))



```



